'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], D=window.ORB, ps=D.poems;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='keats',mode='poem',trail=[],rotation=0,moving=false,lastTime=0;
const mainStops=D.route, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function state(id=selected){const depth=id.endsWith('-floor')?2:id.endsWith('-detail')?1:0;const base=id.replace(/-(floor|detail)$/,'');const pic=base.endsWith('-image');const p=ps.find(x=>base===x.id||base===x.id+'-image')||ps[0];return {p,pic,depth,base,index:mainStops.indexOf(base),root:id==='autumn'};}
function sourceHtml(p){return `<ul class="sources"><li><a href="${p.source}" target="_blank" rel="noopener">Poem text & edition ↗</a></li><li><a href="${p.artReference.url}" target="_blank" rel="noopener">Related historical artwork: ${esc(p.artReference.title)} ↗</a></li></ul>`;}
function show(id,record=true){if(id!=='autumn'&&!/^(keats|dickinson|dunbar|jackson|stevenson|blake)(-image)?(-detail|-floor)?$/.test(id))id='keats';if(record&&id!==selected)trail.push(selected);selected=id;updateHash();render();}
function updateHash(){history.replaceState(null,'','#'+selected+(mode==='poem'?'':'?layer='+mode));}
function render(){const {p,pic,depth,base,index,root}=state();document.body.classList.toggle('focus-image',pic&&depth===0);$('#scene').src=p.image+'.jpg';$('#scene').alt=p.alt;$$('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));let html='';
 if(root){html=`<p class="kicker">THE ANCHOR / AUTUMN</p><h2>A season, many voices.</h2><div class="prose"><p>This is a curated encounter with six enduring English-language autumn poems, not an objective ranking or a survey of every poetic tradition. Each writer brings a different way of seeing: ripeness, adornment, delight, splendor, warmth, and what remains.</p><p>The two orbits alternate a complete poem with an image pause. They form a thematic walk; the order is not a historical timeline. Choose any point, or follow Forward through all twelve stops.</p><p>UP broadens the view. DOWN enters close reading and then a clearly labeled interpretive question. LEFT and RIGHT visit neighboring poems or neighboring images. FORWARD and BACKWARD follow the alternating journey. Viewing history retraces your own visits.</p><p>The guided layer is original companion prose, written as a continuous imagined walk. It is available as text and has not been recorded.</p></div>`;}
 else if(depth===2){html=`<p class="kicker">KNOWLEDGE FLOOR / INTERPRETIVE QUESTION</p><h2>${pic?'What can an image tell?':'An open reading'}</h2><p class="byline">${esc(p.author)} · ${esc(p.title)}</p><div class="prose"><p>${pic?'How does this modern image change which details you notice in the poem?':esc(p.question)}</p><h3>What is established</h3><p>${esc(p.edition)} ${pic?'The displayed image is a newly generated illustration. Its resemblance to a poetic detail does not demonstrate a historical connection.':''}</p><h3>Where this orb stops</h3><p>${pic?'The pairing is a curatorial choice, not evidence of the poet’s visual intention. Compare reading the poem before and after seeing the image; record what the picture foregrounds and what it leaves out.':esc(p.investigation)}</p><p>This is an invitation to further interpretation, not a claim that scholarship has no answer or that one emotional response is correct.</p></div>${sourceHtml(p)}`;}
 else if(depth===1){html=`<p class="kicker">DOWN / A CLOSER LOOK</p><h2>${pic?'Reading the pairing':'Inside the lines'}</h2><p class="byline">${esc(p.author)} · ${esc(p.title)}</p><div class="prose"><p>${esc(pic?p.imageReading:p.detail)}</p>${pic?`<p>The linked historical artwork offers a separate comparison. It is not the image displayed above, and this pairing does not assert that the artist influenced the poet.</p>`:''}</div>${sourceHtml(p)}<p class="source-note">Use DOWN again for the interpretive question and the limits of this reading.</p>`;}
 else if(mode==='feel'){html=`<p class="kicker">ORB FEEL & EXPERIENCE / ${index+1} OF 12</p><h2>${esc(pic?p.imageTitle:p.theme)}</h2><span class="availability">Guided Audio Journey · complete text script · unrecorded</span><div class="prose"><p>${esc(pic?p.imageFeel:p.feel)}</p></div><p class="byline">Original guided companion prose · paired with ${esc(p.author)}’s “${esc(p.title)}”</p><button class="text-action" id="read-start">Read from the beginning</button><button class="text-action" id="whole-journey">Read the continuous journey</button>${sourceHtml(p)}`;}
 else if(mode==='history'){html=`<p class="kicker">${esc(p.theme)} / CONTEXT & INTERPRETATION</p><h2>${esc(p.title)}</h2><p class="byline">${esc(p.author)} (${p.dates}) · ${p.date}</p><div class="prose"><h3>In its time</h3><p>${esc(p.history)}</p><h3>A way into the poem</h3><p>${esc(p.reading)}</p>${pic?`<h3>The image pause</h3><p>${esc(p.imageReading)}</p>`:''}</div><p class="edition">${esc(p.edition)}</p>${sourceHtml(p)}`;}
 else if(pic){html=`<p class="kicker">IMAGE PAUSE / ${index+1} OF 12</p><h2>${esc(p.imageTitle)}</h2><p class="byline">A visual companion to ${esc(p.author)}</p><div class="prose"><p>${esc(p.imageReading)}</p></div><p class="edition">Original AI-generated illustration · FLUX.2 Klein · 2026. This is an imagined scene, not a documentary photograph. <a href="media-credits.json">Image provenance ↗</a></p>`;}
 else{html=`<p class="kicker">POEM ${ps.indexOf(p)+1} / ${esc(p.theme)}</p><h2>${esc(p.title)}</h2><p class="byline">${esc(p.author)} <span>(${p.dates})</span> · ${p.date}</p><pre class="poem">${esc(p.poem)}</pre><p class="edition">PUBLIC-DOMAIN TEXT<br>${esc(p.edition)}</p>${sourceHtml(p)}`;}
 $('#reading').innerHTML=html;$('#route-count').textContent=root?'THE ANCHOR':`${String(index+1).padStart(2,'0')} / 12`;
 $('#previous').disabled=root||index<=0;$('#next').disabled=!root&&index===11;$('#next').textContent=root?'Begin the route →':index===11?'Journey complete':'Next stop →';$('#history').disabled=trail.length===0;
 $('[data-move="up"]').disabled=root;$('[data-move="down"]').disabled=depth===2;$('[data-move="backward"]').disabled=root||index===0;$('[data-move="forward"]').disabled=!root&&index===11;
 $('#edge-note').textContent=depth===2?'Deeper reading ends at this authored question. Continue in Orbiverse to investigate.':root?'DOWN enters the first poem; LEFT and RIGHT select the seasonal neighbors.':index===11?'The authored route ends here. The neighboring orbits remain open.':'Poems and image pauses alternate along the route.';
 $$('.point').forEach(b=>{const yes=b.dataset.point===base;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});
 if($('#read-start'))$('#read-start').onclick=()=>show(mainStops[0]);if($('#whole-journey'))$('#whole-journey').onclick=wholeJourney;
 draw();}
function move(dir){const {p,pic,depth,index,root}=state();const suffix=depth===2?'-floor':depth===1?'-detail':'';let id;
 if(dir==='up')id=depth===2?state().base+'-detail':depth===1?state().base:'autumn';
 if(dir==='down')id=root?'keats':depth===0?state().base+'-detail':depth===1?state().base+'-floor':null;
 if(dir==='left'||dir==='right'){const n=(ps.indexOf(p)+(dir==='left'?-1:1)+6)%6;id=ps[n].id+(pic?'-image':'')+suffix;}
 if(dir==='forward')id=root?'keats':mainStops[index+1];if(dir==='backward')id=mainStops[index-1];if(id)show(id);}
function modal(content){$('#modal-body').innerHTML=content;$('#modal').showModal();}
function wholeJourney(){modal(`<p class="kicker">SPIRAL COURSES / TEXT EDITION</p><h2>ORB Feel & Experience</h2><p>Guided Audio Journey · unrecorded</p><div class="prose">${D.guided.passages.map(x=>`<p>${esc(x.text)}</p>`).join('')}</div><p><a href="guided-journey.md" download>Download the complete script</a></p>`);}
function about(){modal(`<p class="kicker">A NOTE ON THIS ANTHOLOGY</p><h2>Words with their names intact.</h2><p>Six complete poems by John Keats, Emily Dickinson, Paul Laurence Dunbar, Helen Hunt Jackson, Robert Louis Stevenson, and William Blake. This is a personal selection of enduring autumn poems in English, chosen for contrasting moods and a connected route.</p><p>All six underlying poems were published in the eighteenth or nineteenth century, in editions now in the U.S. public domain. No modern protected poems, translations, scholarly annotations, or recordings are reproduced. Dickinson’s version is the early published text, explicitly identified on her point.</p><p>Historical notes and interpretive readings are newly authored. The guided journey is original second-person prose and is <strong>unrecorded</strong>. The six images are original AI-generated scenes made locally with FLUX.2 Klein; they are labeled illustrations, not real photographs or historical evidence.</p><p>The museum artworks linked in the source notes are separate visual references. They are not reproduced here and are not claimed as influences on the poems. Our displayed illustrations are the modern companions.</p><p>Conceptual depth and route order are separate: the double rings carry twelve main stops, while DOWN offers close readings and interpretive questions. The map is not a scientific model of time, geography, or literary influence.</p><p>Offline: keep this folder together, or extract the supplied ZIP. The poems, images, navigation, and guided script work locally; external sources and the archive require internet access.</p><p><a href="media-credits.json">Image provenance</a> · <a href="rights-and-sources.md">Rights & source register</a> · <a href="orb.json">Structured ORB data</a></p><p>${esc(D.authorship)}</p>`);}
const canvas=$('#orb-canvas'),ctx=canvas.getContext('2d'),host=$('#orb');
function coord(angle,ring,w,h){const radius=Math.min(w*.37,h*.4),rx=radius*(ring?1:.88),ry=radius*(ring?.92:.80),tilt=-.08;const a=angle+rotation;let x=Math.cos(a)*rx,y=Math.sin(a)*ry;return {x:w/2+x*Math.cos(tilt)-y*Math.sin(tilt),y:h/2+x*Math.sin(tilt)+y*Math.cos(tilt),z:Math.sin(a)};}
function draw(){const w=host.clientWidth,h=host.clientHeight,dpr=devicePixelRatio||1;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const r=Math.min(w*.32,h*.36);const glow=ctx.createRadialGradient(w/2,h/2,0,w/2,h/2,r*1.28);glow.addColorStop(0,'#9b673918');glow.addColorStop(1,'#9b673900');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.lineWidth=.6;ctx.strokeStyle='#ab8e6133';
 for(let k=-2;k<=2;k++){ctx.beginPath();ctx.ellipse(w/2,h/2+k*r*.31,r*Math.sqrt(1-(k*.31)**2),r*.19,0,0,Math.PI*2);ctx.stroke();}for(let a of [-.75,0,.75]){ctx.beginPath();ctx.ellipse(w/2,h/2,r*.5,r,a,0,Math.PI*2);ctx.stroke();}
 for(let ring=0;ring<2;ring++){ctx.beginPath();for(let i=0;i<=180;i++){const q=coord(i/180*Math.PI*2,ring,w,h);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);}ctx.strokeStyle=ring===0?'#d8ac7388':'#dbb27755';ctx.lineWidth=ring===0?1.1:1;ctx.stroke();}
 ps.forEach((p,i)=>{for(let ring=0;ring<2;ring++){const angle=-Math.PI/2+(i+(ring?.5:0))*Math.PI/3;const q=coord(angle,ring,w,h);const el=document.querySelector(`[data-point="${p.id+(ring?'-image':'')}"]`);el.style.left=q.x+'px';el.style.top=q.y+'px';el.style.zIndex=Math.round(10+q.z*3);}});}
ps.forEach((p,i)=>{for(let ring=0;ring<2;ring++){let id=p.id+(ring?'-image':'');const b=document.createElement('button');b.className='point';b.dataset.point=id;b.setAttribute('aria-label',ring?`Image pause: ${p.imageTitle}`:`${p.title} by ${p.author}`);b.innerHTML=ring?`<img src="${p.image}.jpg" alt=""><span class="label">${String(i+1).padStart(2,'0')} ◇</span>`:`<span class="dot"></span><span class="label">${esc(p.author.split(' ').at(-1))}</span>`;b.onclick=()=>show(id);$('#orb-points').append(b);const li=document.createElement('li');li.innerHTML=`<button data-jump="${id}">${String(i*2+ring+1).padStart(2,'0')} ${ring?'◇ '+esc(p.imageTitle):esc(p.author)+' / '+esc(p.title)}</button>`;$('#point-index').append(li);}});
$$('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));$$('[data-move]').forEach(b=>b.onclick=()=>move(b.dataset.move));$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;updateHash();render();});
$('#previous').onclick=()=>move('backward');$('#next').onclick=()=>move('forward');$('#history').onclick=()=>{const id=trail.pop();if(id)show(id,false);};$('#print').onclick=()=>window.print();$('#about').onclick=about;$('.close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
$('#expand-image').onclick=()=>{const {p}=state();modal(`<h2>${esc(p.imageTitle)}</h2><img src="${p.image}.jpg" alt="${esc(p.alt)}"><p>Original AI-generated illustration · imagined scene · FLUX.2 Klein</p>`);};
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#copy-status').textContent='Point link copied';}catch{modal(`<h2>Your point link</h2><textarea readonly>${esc(location.href)}</textarea>`);}};
$('#continue').onclick=()=>{const {p,base,depth}=state();const text=`Continue an Orbiverse exploration from “Autumn, in Two Orbits.” Anchor: seasonal poetry. Point: ${selected}; layer: ${mode}; conceptual depth: ${depth}. Poem: ${p.title} by ${p.author}. Source: ${p.source}. Trail: ${[...trail,selected].join(' → ')}. Investigate ${depth===2?p.question:'the relationship between '+p.theme.toLowerCase()+' and the season'}. Preserve poem attribution and public-domain editions. Distinguish historical evidence, interpretation, and imagined scenes. The image is AI-generated. Keep UP/DOWN as broader/deeper, LEFT/RIGHT as siblings, FORWARD/BACKWARD as the authored thread. Please extend this point using verified sources.`;modal(`<h2>Continue in Orbiverse</h2><p>Copy this checkpoint into a new ORB conversation. This static reader does not contact an AI service.</p><textarea readonly>${esc(text)}</textarea><button class="text-action" id="copy-prompt">Copy continuation prompt</button><span id="prompt-status" role="status"></span>`);$('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText(text);$('#prompt-status').textContent='Copied';}catch{$('textarea').select();$('#prompt-status').textContent='Select and copy the text above';}};};
function tick(t){if(moving){if(lastTime)rotation+=(t-lastTime)*.000035;draw();lastTime=t;requestAnimationFrame(tick);}else lastTime=0;}
$('#motion').onclick=()=>{moving=!moving;$('#motion').textContent=moving?'Pause motion':'Set in motion';$('#motion').setAttribute('aria-pressed',String(moving));if(moving)requestAnimationFrame(tick);};host.addEventListener('pointerenter',()=>{if(moving){moving=false;lastTime=0;$('#motion').textContent='Set in motion';$('#motion').setAttribute('aria-pressed','false');}});
window.addEventListener('resize',draw);document.addEventListener('keydown',e=>{if($('#modal').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const d={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',PageDown:'forward',PageUp:'backward'}[e.key];if(d){e.preventDefault();move(d);}});
function hash(){const [id,query]=decodeURIComponent(location.hash.slice(1)).split('?');const m=new URLSearchParams(query).get('layer');mode=['poem','history','feel'].includes(m)?m:'poem';show(id||'keats',false);}window.addEventListener('hashchange',hash);hash();


