'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], D=window.ORB, ps=D.poems;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='keats',mode='poem',trail=[],rotation=0,moving=false,lastTime=0;
const mainStops=D.route, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function state(id=selected){const depth=id.endsWith('-floor')?2:id.endsWith('-detail')?1:0;const base=id.replace(/-(floor|detail)$/,'');const pic=base.endsWith('-image');const p=ps.find(x=>base===x.id||base===x.id+'-image')||ps[0];return {p,pic,depth,base,index:mainStops.indexOf(base),root:id==='autumn'};}
function proseHtml(text){return text.split(/\n\n+/).map(p=>`<p>${esc(p)}</p>`).join('');}
function photoCredit(p){return `<a href="${p.photo.sourceUrl}" target="_blank" rel="noopener">${esc(p.photo.photographer)} ↗</a> · <a href="${p.photo.licenseUrl}" target="_blank" rel="noopener">${esc(p.photo.license)}</a><br>${esc(p.photo.location)}`;}
function sourceHtml(p){return `<ul class="sources"><li>${photoCredit(p)}</li><li><a href="${p.source}" target="_blank" rel="noopener">Poem text & edition ↗</a></li><li><a href="${p.artReference.url}" target="_blank" rel="noopener">Related historical artwork: ${esc(p.artReference.title)} ↗</a></li></ul>`;}
function show(id,record=true){if(id!=='autumn'&&!/^(keats|dickinson|dunbar|jackson|stevenson|blake)(-image)?(-detail|-floor)?$/.test(id))id='keats';if(record&&id!==selected)trail.push(selected);selected=id;updateHash();render();}
function updateHash(){history.replaceState(null,'','#'+selected+(mode==='poem'?'':'?layer='+mode));}
function render(){const {p,pic,depth,base,index,root}=state();document.body.classList.toggle('focus-image',pic&&depth===0);$('#scene').src=p.image+'.jpg?v=pnw-v3';$('#scene').alt=p.alt;$('.image-kind').innerHTML=photoCredit(p);$$('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));let html='';
 if(root){html=`<p class="kicker">THE ANCHOR / AUTUMN</p><h2>A season, many voices.</h2><div class="prose"><p>This is a curated encounter with six enduring English-language autumn poems, not an objective ranking or a survey of every poetic tradition. Each writer brings a different way of seeing: ripeness, adornment, delight, splendor, warmth, and what remains.</p><p>Two intertwined strands of words and photographs follow one continuous spiral, alternating a complete poem with an image pause. They form a thematic walk; the order is not a historical timeline. Choose any point, or follow Forward through all twelve stops.</p><p>UP broadens the view. DOWN enters close reading and then a clearly labeled interpretive question. LEFT and RIGHT visit neighboring poems or neighboring images. FORWARD and BACKWARD follow the alternating journey. Viewing history retraces your own visits.</p><p>The guided layer is original companion prose, written as a continuous imagined walk. It is available as text and has not been recorded.</p></div>`;}
 else if(depth===2){html=`<p class="kicker">KNOWLEDGE FLOOR / INTERPRETIVE QUESTION</p><h2>${pic?'What can an image tell?':'An open reading'}</h2><p class="byline">${esc(p.author)} · ${esc(p.title)}</p><div class="prose"><p>${pic?'How does this modern image change which details you notice in the poem?':esc(p.question)}</p><h3>What is established</h3><p>${esc(p.edition)} ${pic?'The displayed image is a documented photograph with a credited photographer and reuse license. Its resemblance to a poetic detail does not demonstrate a historical connection.':''}</p><h3>Where this orb stops</h3><p>${pic?'The pairing is a curatorial choice, not evidence of the poet’s visual intention. Compare reading the poem before and after seeing the image; record what the picture foregrounds and what it leaves out.':esc(p.investigation)}</p><p>This is an invitation to further interpretation, not a claim that scholarship has no answer or that one emotional response is correct.</p></div>${sourceHtml(p)}`;}
 else if(depth===1){html=`<p class="kicker">DOWN / A CLOSER LOOK</p><h2>${pic?'Reading the pairing':'Inside the lines'}</h2><p class="byline">${esc(p.author)} · ${esc(p.title)}</p><div class="prose"><p>${esc(pic?p.imageReading:p.detail)}</p>${pic?`<p>The linked historical artwork offers a separate comparison. It is not the image displayed above, and this pairing does not assert that the artist influenced the poet.</p>`:''}</div>${sourceHtml(p)}<p class="source-note">Use DOWN again for the interpretive question and the limits of this reading.</p>`;}
 else if(mode==='feel'){html=`<p class="kicker">ORB FEEL & EXPERIENCE / ${index+1} OF 12</p><h2>${esc(pic?p.imageTitle:p.theme)}</h2><span class="availability">Guided Audio Journey · revised text · unrecorded</span><div class="prose">${proseHtml(pic?p.imageFeel:p.feel)}</div><p class="byline">Original guided companion prose · paired with ${esc(p.author)}’s “${esc(p.title)}”</p><button class="text-action" id="read-start">Read from the beginning</button><button class="text-action" id="whole-journey">Read the continuous journey</button>${sourceHtml(p)}`;}
 else if(mode==='history'){html=`<p class="kicker">${esc(p.theme)} / CONTEXT & INTERPRETATION</p><h2>${esc(p.title)}</h2><p class="byline">${esc(p.author)} (${p.dates}) · ${p.date}</p><div class="prose"><h3>In its time</h3><p>${esc(p.history)}</p><h3>A way into the poem</h3><p>${esc(p.reading)}</p>${pic?`<h3>The image pause</h3><p>${esc(p.imageReading)}</p>`:''}</div><p class="edition">${esc(p.edition)}</p>${sourceHtml(p)}`;}
 else if(pic){html=`<p class="kicker">IMAGE PAUSE / ${index+1} OF 12</p><h2>${esc(p.imageTitle)}</h2><p class="byline">A visual companion to ${esc(p.author)}</p><div class="prose"><p>${esc(p.imageReading)}</p></div><p class="edition">${photoCredit(p)}. <a href="media-credits.json">Photo provenance ↗</a></p>`;}
 else{html=`<p class="kicker">POEM ${ps.indexOf(p)+1} / ${esc(p.theme)}</p><h2>${esc(p.title)}</h2><p class="byline">${esc(p.author)} <span>(${p.dates})</span> · ${p.date}</p><pre class="poem">${esc(p.poem)}</pre><p class="edition">PUBLIC-DOMAIN TEXT<br>${esc(p.edition)}</p>${sourceHtml(p)}`;}
 $('#reading').innerHTML=html;$('#route-count').textContent=root?'THE ANCHOR':`${String(index+1).padStart(2,'0')} / 12`;
 $('#previous').disabled=root||index<=0;$('#next').disabled=!root&&index===11;$('#next').textContent=root?'Begin the route →':index===11?'Journey complete':'Next stop →';$('#history').disabled=trail.length===0;
 $('[data-move="up"]').disabled=root;$('[data-move="down"]').disabled=depth===2;$('[data-move="backward"]').disabled=root||index===0;$('[data-move="forward"]').disabled=!root&&index===11;
 $('#edge-note').textContent=depth===2?'Deeper reading ends at this authored question. Continue in Orbiverse to investigate.':root?'DOWN enters the first poem; LEFT and RIGHT select the seasonal neighbors.':index===11?'The authored route ends here. The neighboring orbits remain open.':'Poems and image pauses alternate along the route.';
 $$('.point').forEach(b=>{const yes=b.dataset.point===base;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});
 if($('#read-start'))$('#read-start').onclick=()=>show(mainStops[0]);if($('#whole-journey'))$('#whole-journey').onclick=wholeJourney;
 draw();}
function move(dir){const {p,pic,depth,index,root}=state();const suffix=depth===2?'-floor':depth===1?'-detail':'';let id;
 if(dir==='up')id=depth===2?state().base+'-detail':depth===1?state().base:'autumn';
 if(dir==='down')id=root?'keats':depth===0?state().base+'-detail':depth===1?state().base+'-floor':null;
 if(dir==='left'||dir==='right'){const n=(ps.indexOf(p)+(dir==='left'?-1:1)+6)%6;id=ps[n].id+(pic?'-image':'')+suffix;}
 if(dir==='forward')id=root?'keats':mainStops[index+1];if(dir==='backward')id=mainStops[index-1];if(id)show(id);}
function modal(content){$('#modal-body').innerHTML=content;$('#modal').showModal();}
function wholeJourney(){modal(`<p class="kicker">SPIRAL COURSES / TEXT EDITION</p><h2>ORB Feel & Experience</h2><p>${esc(D.guided.title)}<br>Guided Audio Journey · revised text · unrecorded</p><div class="prose">${D.guided.passages.map(x=>proseHtml(x.text)).join('')}</div><p><a href="guided-journey-pnw-v3.md" download>Download the complete script</a></p>`);}
function about(){modal(`<p class="kicker">A NOTE ON THIS ANTHOLOGY</p><h2>Words with their names intact.</h2><p>Six complete poems by John Keats, Emily Dickinson, Paul Laurence Dunbar, Helen Hunt Jackson, Robert Louis Stevenson, and William Blake. This is a personal selection of enduring autumn poems in English, chosen for contrasting moods and a connected route.</p><p>All six underlying poems were published in the eighteenth or nineteenth century, in editions now in the U.S. public domain. No modern protected poems, translations, or scholarly annotations are reproduced. Dickinson’s version is the early published text, explicitly identified on her point.</p><p>Historical notes and interpretive readings are newly authored. The guided journey is original second-person prose and is <strong>unrecorded</strong>. The six images are documented photographs of autumn leaves in Seattle and Portland, dated 1983–2020. Their individual Creative Commons licenses, dates, places, and credits are linked at every stop. No generated imagery is used. Their relationship to the poems is a curatorial pairing; they do not document the poets’ lives.</p><p>The museum artworks linked in the source notes are separate visual references. They are not reproduced here and are not claimed as influences on the poems. The photographs are regional companions; the poets are not presented as Pacific Northwest writers.</p><p><strong>Optional piano:</strong> “Gymnopédie No. 1,” composed by Erik Satie; recording by <a href="${D.music.sourceUrl}" target="_blank" rel="noopener">Kevin MacLeod (incompetech.com)</a>, used under <a href="${D.music.licenseUrl}" target="_blank" rel="noopener">Creative Commons Attribution 4.0</a>. The original recording is unchanged. Playback offers a soft start, volume, and repeat controls. This is instrumental accompaniment; the guided script remains unrecorded.</p><p>Conceptual depth and route order are separate: the continuous spiral carries twelve alternating poem and photo stops, while DOWN offers close readings and interpretive questions. The map is not a scientific model of time, geography, or literary influence.</p><p>Offline: keep this folder together, or extract the supplied ZIP. The poems, images, piano, navigation, and guided script work locally; external sources and the archive require internet access.</p><p><a href="media-credits.json">Image provenance</a> · <a href="music-credits.json">Music credit</a> · <a href="rights-and-sources.md">Rights & source register</a> · <a href="orb.json">Structured ORB data</a></p><p>${esc(D.authorship)}</p>`);}
const canvas=$('#orb-canvas'),ctx=canvas.getContext('2d'),host=$('#orb');
function coord(t,w,h){
 const y=-.92+1.84*t, radius=Math.min(w*.39,178), ry=Math.min(h*.43,220);
 const angle=-Math.PI/2+.42+t*Math.PI*4+rotation, ring=Math.sqrt(1-y*y), z=ring*Math.sin(angle);
 return {x:w/2+radius*ring*Math.cos(angle),y:h/2+ry*y+z*ry*.075,z};
}
function draw(){
 const w=host.clientWidth,h=host.clientHeight,dpr=devicePixelRatio||1;
 if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const rx=Math.min(w*.39,178),ry=Math.min(h*.43,220),cx=w/2,cy=h/2;
 const glow=ctx.createRadialGradient(cx-rx*.3,cy-ry*.25,0,cx,cy,ry*1.2);glow.addColorStop(0,'#fff7c29c');glow.addColorStop(1,'#fff7c200');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
 ctx.lineWidth=.7;ctx.strokeStyle='#9b572745';ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);ctx.stroke();
 for(let y of [-.66,-.33,0,.33,.66]){ctx.beginPath();ctx.ellipse(cx,cy+y*ry,rx*Math.sqrt(1-y*y),ry*.065,0,0,Math.PI*2);ctx.stroke();}
 for(let k of [.28,.65]){ctx.beginPath();ctx.ellipse(cx,cy,rx*k,ry,0,0,Math.PI*2);ctx.stroke();}
 const active=state().root?-1:state().index/11;
 for(let i=1;i<=440;i++){
  const t=i/440,p=coord((i-1)/440,w,h),q=coord(t,w,h),front=(p.z+q.z)>0;
  ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.lineWidth=front?2.8:1.7;
  ctx.strokeStyle=t<=active?(front?'#a72f18':'#b9653eaa'):(front?'#b45320':'#aa744788');
  ctx.shadowColor='#fff4c6';ctx.shadowBlur=front?9:2;ctx.stroke();
 }
 ctx.shadowBlur=0;
 mainStops.forEach((id,i)=>{const q=coord(i/11,w,h),el=document.querySelector(`[data-point="${id}"]`);el.style.left=q.x+'px';el.style.top=q.y+'px';el.classList.toggle('photo-left',q.x<w/2);el.style.zIndex=id===state().base?30:Math.round(10+q.z*3);});
 const q=coord(Math.max(0,active),w,h);if(active>=0){ctx.beginPath();ctx.arc(q.x,q.y,22,0,Math.PI*2);ctx.strokeStyle='#a72f1880';ctx.lineWidth=1;ctx.stroke();}
}
ps.forEach((p,i)=>{for(let ring=0;ring<2;ring++){let id=p.id+(ring?'-image':'');const b=document.createElement('button');b.className='point';b.dataset.point=id;b.setAttribute('aria-label',ring?`Image pause: ${p.imageTitle}`:`${p.title} by ${p.author}`);b.innerHTML=ring?`<img src="${p.image}.jpg?v=pnw-v3" alt=""><span class="label">${String(i*2+2).padStart(2,'0')} ◇</span>`:`<span class="dot"></span><span class="label">${String(i*2+1).padStart(2,'0')} ${esc(p.author.split(' ').at(-1))}</span>`;b.onclick=()=>show(id);$('#orb-points').append(b);const li=document.createElement('li');li.innerHTML=`<button data-jump="${id}">${String(i*2+ring+1).padStart(2,'0')} ${ring?'◇ '+esc(p.imageTitle):esc(p.author)+' / '+esc(p.title)}</button>`;$('#point-index').append(li);}});
$$('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));$$('[data-move]').forEach(b=>b.onclick=()=>move(b.dataset.move));$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;if(mode==='feel'&&state().depth>0){show(state().base);}else{updateHash();render();}});
$('#previous').onclick=()=>move('backward');$('#next').onclick=()=>move('forward');$('#history').onclick=()=>{const id=trail.pop();if(id)show(id,false);};$('#print').onclick=()=>window.print();$('#about').onclick=about;$('.close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
$('#expand-image').onclick=()=>{const {p}=state();modal(`<h2>${esc(p.imageTitle)}</h2><img src="${p.image}.jpg?v=pnw-v3" alt="${esc(p.alt)}"><p>${photoCredit(p)}</p>`);};
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#copy-status').textContent='Point link copied';}catch{modal(`<h2>Your point link</h2><textarea readonly>${esc(location.href)}</textarea>`);}};
$('#continue').onclick=()=>{const {p,base,depth}=state();const text=`Continue an Orbiverse exploration from “Autumn in the Pacific Northwest.” Anchor: seasonal poetry. Point: ${selected}; layer: ${mode}; conceptual depth: ${depth}. Poem: ${p.title} by ${p.author}. Source: ${p.source}. Trail: ${[...trail,selected].join(' → ')}. Investigate ${depth===2?p.question:'the relationship between '+p.theme.toLowerCase()+' and the season'}. Preserve poem attribution and public-domain editions. Distinguish historical evidence, interpretation, and imagined scenes. The image is a licensed photograph by ${p.photo.photographer}; source: ${p.photo.sourceUrl}. Keep the photographer credit and license. Keep UP/DOWN as broader/deeper, LEFT/RIGHT as siblings, FORWARD/BACKWARD as the authored thread. Please extend this point using verified sources.`;modal(`<h2>Continue in Orbiverse</h2><p>Copy this checkpoint into a new ORB conversation. This static reader does not contact an AI service.</p><textarea readonly>${esc(text)}</textarea><button class="text-action" id="copy-prompt">Copy continuation prompt</button><span id="prompt-status" role="status"></span>`);$('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText(text);$('#prompt-status').textContent='Copied';}catch{$('textarea').select();$('#prompt-status').textContent='Select and copy the text above';}};};
function tick(t){if(moving){if(lastTime)rotation+=(t-lastTime)*.000035;draw();lastTime=t;requestAnimationFrame(tick);}else lastTime=0;}
$('#motion').onclick=()=>{moving=!moving;$('#motion').textContent=moving?'Pause motion':'Set in motion';$('#motion').setAttribute('aria-pressed',String(moving));if(moving)requestAnimationFrame(tick);};host.addEventListener('pointerenter',()=>{if(moving){moving=false;lastTime=0;$('#motion').textContent='Set in motion';$('#motion').setAttribute('aria-pressed','false');}});
window.addEventListener('resize',draw);document.addEventListener('keydown',e=>{if($('#modal').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const d={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',PageDown:'forward',PageUp:'backward'}[e.key];if(d){e.preventDefault();move(d);}});
function hash(){const [id,query]=decodeURIComponent(location.hash.slice(1)).split('?');const m=new URLSearchParams(query).get('layer');mode=['poem','history','feel'].includes(m)?m:'poem';show(id||'keats',false);}window.addEventListener('hashchange',hash);hash();



// Optional accompaniment stays independent of the reading route.
const music=$('#autumn-music'),musicToggle=$('#music-toggle'),volume=$('#music-volume');
let musicStarting=false,fadeFrame=0;
const chosenVolume=()=>Number(volume.value)/100;
function musicUI(){musicToggle.textContent=music.paused?'▶ Play music':'Ⅱ Pause music';musicToggle.setAttribute('aria-pressed',String(!music.paused));}
music.volume=chosenVolume();
musicToggle.onclick=async()=>{
 if(musicStarting)return;
 cancelAnimationFrame(fadeFrame);
 if(!music.paused){music.pause();music.volume=chosenVolume();$('#music-status').textContent='Paused — continue whenever you wish.';return;}
 musicStarting=true;musicToggle.disabled=true;music.volume=0;$('#music-status').textContent='Opening the piano…';
 try{await music.play();musicUI();$('#music-status').textContent='Quiet piano for your autumn walk.';const start=performance.now();const fade=now=>{music.volume=chosenVolume()*Math.max(0,Math.min(1,(now-start)/1200));if(now-start<1200&&!music.paused)fadeFrame=requestAnimationFrame(fade);};fadeFrame=requestAnimationFrame(fade);}
 catch{musicUI();$('#music-status').textContent='Music could not load. Press play to try again.';}
 finally{musicStarting=false;musicToggle.disabled=false;}
};
volume.oninput=()=>{cancelAnimationFrame(fadeFrame);music.volume=chosenVolume();$('#music-volume-value').value=volume.value+'%';};
$('#music-repeat').onchange=()=>{music.loop=$('#music-repeat').checked;};
music.addEventListener('pause',musicUI);music.addEventListener('play',musicUI);
music.addEventListener('ended',()=>{musicUI();$('#music-status').textContent='The piano has come to rest. Play again whenever you wish.';});
music.addEventListener('error',()=>{musicUI();$('#music-status').textContent='Music could not load. Press play to try again.';});
